# Generated by Django 5.0.2 on 2024-02-26 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_news_content_alter_news_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_news',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 18, 32, 58, 566696, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 18, 32, 58, 565673, tzinfo=datetime.timezone.utc)),
        ),
    ]
